syntax = "proto3";

package trade_itg;
// 相对路径;包名
option go_package = "./trade_itg_pb";

message C2cTransferPreReq {
    string buyer_user_id = 1;
}

message C2cTransferPreRsp {
    string buyer_user_id = 1;
    string transaction_id = 2;
}

message C2cTransferDoReq {
    string transaction_id = 1;
    string buyer_user_id = 2;
    string seller_user_id = 3;
    int64 amount = 4;
    int32 cur_type = 5;
    int32 verify_type = 6;
    string password = 7;
    int32 version = 8;  // c2c转账版本
}

message C2cTransferDoRsp {
    string transaction_id = 1;
    string buyer_user_id = 2;
    string seller_user_id = 3;
    int32 is_repeat = 4;
}

message Bank2CPreReq {
    string user_id = 1;
}

message Bank2CPreRsp {
    string user_id = 1;
    string transaction_id = 2;
}

message Bank2CDoReq {
    string transaction_id = 1;
    string user_id = 2;
    int32 bank_type = 3;
    int64 amount = 4;
    string desc = 5;
    int32 verify_type = 6;
    string password = 7;
}

message Bank2CDoRsp {
    string transaction_id = 1;
    string user_id = 2;
    int32 is_repeat = 3;
}

message C2BankPreReq {
    string user_id = 1;
}

message C2BankPreRsp {
    string user_id = 1;
    string transaction_id = 2;
}

message C2BankDoReq {
    string transaction_id = 1;
    string user_id = 2;
    int32 bank_type = 3;
    int64 amount = 4;
    string desc = 5;
    int32 verify_type = 6;
    string password = 7;
}

message C2BankDoRsp {
    string transaction_id = 1;
    string user_id = 2;
    int32 is_repeat = 3;
}

message PayPreReq {
    string user_id = 1;
    string merchant_id = 2;
}

message PayPreRsp {
    string user_id = 1;
    string transaction_id = 2;
}

message BanPayReq {
    string transaction_id = 1;
    string out_order_no = 2;
    string merchant_id = 3;
    string user_id = 4;
    int64 amount = 5;
    int32 verify_type = 6;
    string password = 7;
}

message BanPayRsp {
    string transaction_id = 1;
    string out_order_no = 2;
    string user_id = 3;
    string merchant_id = 4;
    int64 amount = 5;
    string pay_time = 6;
    string order_success_token = 7;
}

message CloseOrSupplyOrderReq {
    string transaction_id = 1;
    string out_order_no = 2;
    string merchant_id = 3;
    string user_id = 4;
    int64 amount = 5;
}

message CloseOrSupplyOrderRsp {
    int32 result_code = 1;
    string transaction_id = 2;
    string user_id = 3;
    string merchant_id = 4;
    int32 trade_state = 5;
    string pay_time = 6;
    string order_success_token = 7;
}

service TradeItg {
    rpc C2cTransferPre(C2cTransferPreReq) returns (C2cTransferPreRsp);
    rpc C2cTransferDo(C2cTransferDoReq) returns (C2cTransferDoRsp);
    rpc Bank2CPre(Bank2CPreReq) returns (Bank2CPreRsp);
    rpc Bank2CDo(Bank2CDoReq) returns (Bank2CDoRsp);
    rpc C2BankPre(C2BankPreReq) returns (C2BankPreRsp);
    rpc C2BankDo(C2BankDoReq) returns (C2BankDoRsp);

    rpc PayPre(PayPreReq) returns (PayPreRsp);
    rpc BanPay(BanPayReq) returns (BanPayRsp);
    rpc CloseOrSupplyOrder(CloseOrSupplyOrderReq) returns (CloseOrSupplyOrderRsp);
}

/*
生成项目框架
goctl rpc protoc trade_itg.proto --go_out=. --go-grpc_out=. --zrpc_out=.
*/