// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: trade_itg.proto

package server

import (
	"context"

	"github.com/starslipay/trade_itg/internal/logic"
	"github.com/starslipay/trade_itg/internal/svc"
	"github.com/starslipay/trade_itg/trade_itg_pb"
)

type TradeItgServer struct {
	svcCtx *svc.ServiceContext
	trade_itg_pb.UnimplementedTradeItgServer
}

func NewTradeItgServer(svcCtx *svc.ServiceContext) *TradeItgServer {
	return &TradeItgServer{
		svcCtx: svcCtx,
	}
}

func (s *TradeItgServer) C2CTransferPre(ctx context.Context, in *trade_itg_pb.C2CTransferPreReq) (*trade_itg_pb.C2CTransferPreRsp, error) {
	l := logic.NewC2cTransferPreLogic(ctx, s.svcCtx)
	return l.C2CTransferPre(in)
}

func (s *TradeItgServer) C2CTransferDo(ctx context.Context, in *trade_itg_pb.C2CTransferDoReq) (*trade_itg_pb.C2CTransferDoRsp, error) {
	l := logic.NewC2cTransferDoLogic(ctx, s.svcCtx)
	return l.C2CTransferDo(in)
}
