// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: trade_itg.proto

package server

import (
	"context"

	"github.com/starslipay/trade_itg/internal/logic"
	"github.com/starslipay/trade_itg/internal/svc"
	"github.com/starslipay/trade_itg/trade_itg_pb"
)

type TradeItgServer struct {
	svcCtx *svc.ServiceContext
	trade_itg_pb.UnimplementedTradeItgServer
}

func NewTradeItgServer(svcCtx *svc.ServiceContext) *TradeItgServer {
	return &TradeItgServer{
		svcCtx: svcCtx,
	}
}

func (s *TradeItgServer) C2CTransferPre(ctx context.Context, in *trade_itg_pb.C2CTransferPreReq) (*trade_itg_pb.C2CTransferPreRsp, error) {
	l := logic.NewC2cTransferPreLogic(ctx, s.svcCtx)
	return l.C2CTransferPre(in)
}

func (s *TradeItgServer) C2CTransferDo(ctx context.Context, in *trade_itg_pb.C2CTransferDoReq) (*trade_itg_pb.C2CTransferDoRsp, error) {
	l := logic.NewC2cTransferDoLogic(ctx, s.svcCtx)
	return l.C2CTransferDo(in)
}

func (s *TradeItgServer) Bank2CPre(ctx context.Context, in *trade_itg_pb.Bank2CPreReq) (*trade_itg_pb.Bank2CPreRsp, error) {
	l := logic.NewBank2CPreLogic(ctx, s.svcCtx)
	return l.Bank2CPre(in)
}

func (s *TradeItgServer) Bank2CDo(ctx context.Context, in *trade_itg_pb.Bank2CDoReq) (*trade_itg_pb.Bank2CDoRsp, error) {
	l := logic.NewBank2CDoLogic(ctx, s.svcCtx)
	return l.Bank2CDo(in)
}

func (s *TradeItgServer) C2BankPre(ctx context.Context, in *trade_itg_pb.C2BankPreReq) (*trade_itg_pb.C2BankPreRsp, error) {
	l := logic.NewC2BankPreLogic(ctx, s.svcCtx)
	return l.C2BankPre(in)
}

func (s *TradeItgServer) C2BankDo(ctx context.Context, in *trade_itg_pb.C2BankDoReq) (*trade_itg_pb.C2BankDoRsp, error) {
	l := logic.NewC2BankDoLogic(ctx, s.svcCtx)
	return l.C2BankDo(in)
}

func (s *TradeItgServer) PayPre(ctx context.Context, in *trade_itg_pb.PayPreReq) (*trade_itg_pb.PayPreRsp, error) {
	l := logic.NewPayPreLogic(ctx, s.svcCtx)
	return l.PayPre(in)
}

func (s *TradeItgServer) BanPay(ctx context.Context, in *trade_itg_pb.BanPayReq) (*trade_itg_pb.BanPayRsp, error) {
	l := logic.NewBanPayLogic(ctx, s.svcCtx)
	return l.BanPay(in)
}

func (s *TradeItgServer) CloseOrSupplyOrder(ctx context.Context, in *trade_itg_pb.CloseOrSupplyOrderReq) (*trade_itg_pb.CloseOrSupplyOrderRsp, error) {
	l := logic.NewCloseOrSupplyOrderLogic(ctx, s.svcCtx)
	return l.CloseOrSupplyOrder(in)
}
