// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: trade_itg.proto

package trade_itg_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type C2CTransferPreReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuyerUserId   string                 `protobuf:"bytes,1,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2CTransferPreReq) Reset() {
	*x = C2CTransferPreReq{}
	mi := &file_trade_itg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2CTransferPreReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CTransferPreReq) ProtoMessage() {}

func (x *C2CTransferPreReq) ProtoReflect() protoreflect.Message {
	mi := &file_trade_itg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CTransferPreReq.ProtoReflect.Descriptor instead.
func (*C2CTransferPreReq) Descriptor() ([]byte, []int) {
	return file_trade_itg_proto_rawDescGZIP(), []int{0}
}

func (x *C2CTransferPreReq) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

type C2CTransferPreRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuyerUserId   string                 `protobuf:"bytes,1,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2CTransferPreRsp) Reset() {
	*x = C2CTransferPreRsp{}
	mi := &file_trade_itg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2CTransferPreRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CTransferPreRsp) ProtoMessage() {}

func (x *C2CTransferPreRsp) ProtoReflect() protoreflect.Message {
	mi := &file_trade_itg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CTransferPreRsp.ProtoReflect.Descriptor instead.
func (*C2CTransferPreRsp) Descriptor() ([]byte, []int) {
	return file_trade_itg_proto_rawDescGZIP(), []int{1}
}

func (x *C2CTransferPreRsp) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *C2CTransferPreRsp) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type C2CTransferDoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	BuyerUserId   string                 `protobuf:"bytes,2,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	SellerUserId  string                 `protobuf:"bytes,3,opt,name=seller_user_id,json=sellerUserId,proto3" json:"seller_user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	CurType       int32                  `protobuf:"varint,5,opt,name=cur_type,json=curType,proto3" json:"cur_type,omitempty"`
	VerifyType    int32                  `protobuf:"varint,6,opt,name=verify_type,json=verifyType,proto3" json:"verify_type,omitempty"`
	Password      string                 `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	Version       int32                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"` // c2c转账版本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2CTransferDoReq) Reset() {
	*x = C2CTransferDoReq{}
	mi := &file_trade_itg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2CTransferDoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CTransferDoReq) ProtoMessage() {}

func (x *C2CTransferDoReq) ProtoReflect() protoreflect.Message {
	mi := &file_trade_itg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CTransferDoReq.ProtoReflect.Descriptor instead.
func (*C2CTransferDoReq) Descriptor() ([]byte, []int) {
	return file_trade_itg_proto_rawDescGZIP(), []int{2}
}

func (x *C2CTransferDoReq) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *C2CTransferDoReq) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *C2CTransferDoReq) GetSellerUserId() string {
	if x != nil {
		return x.SellerUserId
	}
	return ""
}

func (x *C2CTransferDoReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *C2CTransferDoReq) GetCurType() int32 {
	if x != nil {
		return x.CurType
	}
	return 0
}

func (x *C2CTransferDoReq) GetVerifyType() int32 {
	if x != nil {
		return x.VerifyType
	}
	return 0
}

func (x *C2CTransferDoReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *C2CTransferDoReq) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type C2CTransferDoRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	BuyerUserId   string                 `protobuf:"bytes,2,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	SellerUserId  string                 `protobuf:"bytes,3,opt,name=seller_user_id,json=sellerUserId,proto3" json:"seller_user_id,omitempty"`
	IsRepeat      int32                  `protobuf:"varint,4,opt,name=is_repeat,json=isRepeat,proto3" json:"is_repeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2CTransferDoRsp) Reset() {
	*x = C2CTransferDoRsp{}
	mi := &file_trade_itg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2CTransferDoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CTransferDoRsp) ProtoMessage() {}

func (x *C2CTransferDoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_trade_itg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CTransferDoRsp.ProtoReflect.Descriptor instead.
func (*C2CTransferDoRsp) Descriptor() ([]byte, []int) {
	return file_trade_itg_proto_rawDescGZIP(), []int{3}
}

func (x *C2CTransferDoRsp) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *C2CTransferDoRsp) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *C2CTransferDoRsp) GetSellerUserId() string {
	if x != nil {
		return x.SellerUserId
	}
	return ""
}

func (x *C2CTransferDoRsp) GetIsRepeat() int32 {
	if x != nil {
		return x.IsRepeat
	}
	return 0
}

type Bank2CPreReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bank2CPreReq) Reset() {
	*x = Bank2CPreReq{}
	mi := &file_trade_itg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bank2CPreReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bank2CPreReq) ProtoMessage() {}

func (x *Bank2CPreReq) ProtoReflect() protoreflect.Message {
	mi := &file_trade_itg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bank2CPreReq.ProtoReflect.Descriptor instead.
func (*Bank2CPreReq) Descriptor() ([]byte, []int) {
	return file_trade_itg_proto_rawDescGZIP(), []int{4}
}

func (x *Bank2CPreReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Bank2CPreRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bank2CPreRsp) Reset() {
	*x = Bank2CPreRsp{}
	mi := &file_trade_itg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bank2CPreRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bank2CPreRsp) ProtoMessage() {}

func (x *Bank2CPreRsp) ProtoReflect() protoreflect.Message {
	mi := &file_trade_itg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bank2CPreRsp.ProtoReflect.Descriptor instead.
func (*Bank2CPreRsp) Descriptor() ([]byte, []int) {
	return file_trade_itg_proto_rawDescGZIP(), []int{5}
}

func (x *Bank2CPreRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Bank2CPreRsp) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type Bank2CDoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BankType      int32                  `protobuf:"varint,3,opt,name=bank_type,json=bankType,proto3" json:"bank_type,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Desc          string                 `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	VerifyType    int32                  `protobuf:"varint,6,opt,name=verify_type,json=verifyType,proto3" json:"verify_type,omitempty"`
	Password      string                 `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bank2CDoReq) Reset() {
	*x = Bank2CDoReq{}
	mi := &file_trade_itg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bank2CDoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bank2CDoReq) ProtoMessage() {}

func (x *Bank2CDoReq) ProtoReflect() protoreflect.Message {
	mi := &file_trade_itg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bank2CDoReq.ProtoReflect.Descriptor instead.
func (*Bank2CDoReq) Descriptor() ([]byte, []int) {
	return file_trade_itg_proto_rawDescGZIP(), []int{6}
}

func (x *Bank2CDoReq) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Bank2CDoReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Bank2CDoReq) GetBankType() int32 {
	if x != nil {
		return x.BankType
	}
	return 0
}

func (x *Bank2CDoReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Bank2CDoReq) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Bank2CDoReq) GetVerifyType() int32 {
	if x != nil {
		return x.VerifyType
	}
	return 0
}

func (x *Bank2CDoReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Bank2CDoRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsRepeat      int32                  `protobuf:"varint,3,opt,name=is_repeat,json=isRepeat,proto3" json:"is_repeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bank2CDoRsp) Reset() {
	*x = Bank2CDoRsp{}
	mi := &file_trade_itg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bank2CDoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bank2CDoRsp) ProtoMessage() {}

func (x *Bank2CDoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_trade_itg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bank2CDoRsp.ProtoReflect.Descriptor instead.
func (*Bank2CDoRsp) Descriptor() ([]byte, []int) {
	return file_trade_itg_proto_rawDescGZIP(), []int{7}
}

func (x *Bank2CDoRsp) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Bank2CDoRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Bank2CDoRsp) GetIsRepeat() int32 {
	if x != nil {
		return x.IsRepeat
	}
	return 0
}

type C2BankPreReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2BankPreReq) Reset() {
	*x = C2BankPreReq{}
	mi := &file_trade_itg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2BankPreReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2BankPreReq) ProtoMessage() {}

func (x *C2BankPreReq) ProtoReflect() protoreflect.Message {
	mi := &file_trade_itg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2BankPreReq.ProtoReflect.Descriptor instead.
func (*C2BankPreReq) Descriptor() ([]byte, []int) {
	return file_trade_itg_proto_rawDescGZIP(), []int{8}
}

func (x *C2BankPreReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type C2BankPreRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2BankPreRsp) Reset() {
	*x = C2BankPreRsp{}
	mi := &file_trade_itg_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2BankPreRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2BankPreRsp) ProtoMessage() {}

func (x *C2BankPreRsp) ProtoReflect() protoreflect.Message {
	mi := &file_trade_itg_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2BankPreRsp.ProtoReflect.Descriptor instead.
func (*C2BankPreRsp) Descriptor() ([]byte, []int) {
	return file_trade_itg_proto_rawDescGZIP(), []int{9}
}

func (x *C2BankPreRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *C2BankPreRsp) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type C2BankDoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BankType      int32                  `protobuf:"varint,3,opt,name=bank_type,json=bankType,proto3" json:"bank_type,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Desc          string                 `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	VerifyType    int32                  `protobuf:"varint,6,opt,name=verify_type,json=verifyType,proto3" json:"verify_type,omitempty"`
	Password      string                 `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2BankDoReq) Reset() {
	*x = C2BankDoReq{}
	mi := &file_trade_itg_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2BankDoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2BankDoReq) ProtoMessage() {}

func (x *C2BankDoReq) ProtoReflect() protoreflect.Message {
	mi := &file_trade_itg_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2BankDoReq.ProtoReflect.Descriptor instead.
func (*C2BankDoReq) Descriptor() ([]byte, []int) {
	return file_trade_itg_proto_rawDescGZIP(), []int{10}
}

func (x *C2BankDoReq) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *C2BankDoReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *C2BankDoReq) GetBankType() int32 {
	if x != nil {
		return x.BankType
	}
	return 0
}

func (x *C2BankDoReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *C2BankDoReq) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *C2BankDoReq) GetVerifyType() int32 {
	if x != nil {
		return x.VerifyType
	}
	return 0
}

func (x *C2BankDoReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type C2BankDoRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsRepeat      int32                  `protobuf:"varint,3,opt,name=is_repeat,json=isRepeat,proto3" json:"is_repeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2BankDoRsp) Reset() {
	*x = C2BankDoRsp{}
	mi := &file_trade_itg_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2BankDoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2BankDoRsp) ProtoMessage() {}

func (x *C2BankDoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_trade_itg_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2BankDoRsp.ProtoReflect.Descriptor instead.
func (*C2BankDoRsp) Descriptor() ([]byte, []int) {
	return file_trade_itg_proto_rawDescGZIP(), []int{11}
}

func (x *C2BankDoRsp) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *C2BankDoRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *C2BankDoRsp) GetIsRepeat() int32 {
	if x != nil {
		return x.IsRepeat
	}
	return 0
}

type PayPreReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayPreReq) Reset() {
	*x = PayPreReq{}
	mi := &file_trade_itg_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayPreReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayPreReq) ProtoMessage() {}

func (x *PayPreReq) ProtoReflect() protoreflect.Message {
	mi := &file_trade_itg_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayPreReq.ProtoReflect.Descriptor instead.
func (*PayPreReq) Descriptor() ([]byte, []int) {
	return file_trade_itg_proto_rawDescGZIP(), []int{12}
}

func (x *PayPreReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PayPreReq) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type PayPreRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayPreRsp) Reset() {
	*x = PayPreRsp{}
	mi := &file_trade_itg_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayPreRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayPreRsp) ProtoMessage() {}

func (x *PayPreRsp) ProtoReflect() protoreflect.Message {
	mi := &file_trade_itg_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayPreRsp.ProtoReflect.Descriptor instead.
func (*PayPreRsp) Descriptor() ([]byte, []int) {
	return file_trade_itg_proto_rawDescGZIP(), []int{13}
}

func (x *PayPreRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PayPreRsp) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type BanPayReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	OutOrderNo    string                 `protobuf:"bytes,2,opt,name=out_order_no,json=outOrderNo,proto3" json:"out_order_no,omitempty"`
	MerchantId    string                 `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	VerifyType    int32                  `protobuf:"varint,6,opt,name=verify_type,json=verifyType,proto3" json:"verify_type,omitempty"`
	Password      string                 `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanPayReq) Reset() {
	*x = BanPayReq{}
	mi := &file_trade_itg_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanPayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanPayReq) ProtoMessage() {}

func (x *BanPayReq) ProtoReflect() protoreflect.Message {
	mi := &file_trade_itg_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanPayReq.ProtoReflect.Descriptor instead.
func (*BanPayReq) Descriptor() ([]byte, []int) {
	return file_trade_itg_proto_rawDescGZIP(), []int{14}
}

func (x *BanPayReq) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *BanPayReq) GetOutOrderNo() string {
	if x != nil {
		return x.OutOrderNo
	}
	return ""
}

func (x *BanPayReq) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *BanPayReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BanPayReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BanPayReq) GetVerifyType() int32 {
	if x != nil {
		return x.VerifyType
	}
	return 0
}

func (x *BanPayReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type BanPayRsp struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TransactionId     string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	OutOrderNo        string                 `protobuf:"bytes,2,opt,name=out_order_no,json=outOrderNo,proto3" json:"out_order_no,omitempty"`
	UserId            string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MerchantId        string                 `protobuf:"bytes,4,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Amount            int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	PayTime           string                 `protobuf:"bytes,6,opt,name=pay_time,json=payTime,proto3" json:"pay_time,omitempty"`
	OrderSuccessToken string                 `protobuf:"bytes,7,opt,name=order_success_token,json=orderSuccessToken,proto3" json:"order_success_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BanPayRsp) Reset() {
	*x = BanPayRsp{}
	mi := &file_trade_itg_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanPayRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanPayRsp) ProtoMessage() {}

func (x *BanPayRsp) ProtoReflect() protoreflect.Message {
	mi := &file_trade_itg_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanPayRsp.ProtoReflect.Descriptor instead.
func (*BanPayRsp) Descriptor() ([]byte, []int) {
	return file_trade_itg_proto_rawDescGZIP(), []int{15}
}

func (x *BanPayRsp) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *BanPayRsp) GetOutOrderNo() string {
	if x != nil {
		return x.OutOrderNo
	}
	return ""
}

func (x *BanPayRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BanPayRsp) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *BanPayRsp) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BanPayRsp) GetPayTime() string {
	if x != nil {
		return x.PayTime
	}
	return ""
}

func (x *BanPayRsp) GetOrderSuccessToken() string {
	if x != nil {
		return x.OrderSuccessToken
	}
	return ""
}

type CloseOrSupplyOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	OutOrderNo    string                 `protobuf:"bytes,2,opt,name=out_order_no,json=outOrderNo,proto3" json:"out_order_no,omitempty"`
	MerchantId    string                 `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseOrSupplyOrderReq) Reset() {
	*x = CloseOrSupplyOrderReq{}
	mi := &file_trade_itg_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseOrSupplyOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseOrSupplyOrderReq) ProtoMessage() {}

func (x *CloseOrSupplyOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_trade_itg_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseOrSupplyOrderReq.ProtoReflect.Descriptor instead.
func (*CloseOrSupplyOrderReq) Descriptor() ([]byte, []int) {
	return file_trade_itg_proto_rawDescGZIP(), []int{16}
}

func (x *CloseOrSupplyOrderReq) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CloseOrSupplyOrderReq) GetOutOrderNo() string {
	if x != nil {
		return x.OutOrderNo
	}
	return ""
}

func (x *CloseOrSupplyOrderReq) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CloseOrSupplyOrderReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CloseOrSupplyOrderReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CloseOrSupplyOrderRsp struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ResultCode        int32                  `protobuf:"varint,1,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"`
	TransactionId     string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	UserId            string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MerchantId        string                 `protobuf:"bytes,4,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	TradeState        int32                  `protobuf:"varint,5,opt,name=trade_state,json=tradeState,proto3" json:"trade_state,omitempty"`
	PayTime           string                 `protobuf:"bytes,6,opt,name=pay_time,json=payTime,proto3" json:"pay_time,omitempty"`
	OrderSuccessToken string                 `protobuf:"bytes,7,opt,name=order_success_token,json=orderSuccessToken,proto3" json:"order_success_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CloseOrSupplyOrderRsp) Reset() {
	*x = CloseOrSupplyOrderRsp{}
	mi := &file_trade_itg_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseOrSupplyOrderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseOrSupplyOrderRsp) ProtoMessage() {}

func (x *CloseOrSupplyOrderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_trade_itg_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseOrSupplyOrderRsp.ProtoReflect.Descriptor instead.
func (*CloseOrSupplyOrderRsp) Descriptor() ([]byte, []int) {
	return file_trade_itg_proto_rawDescGZIP(), []int{17}
}

func (x *CloseOrSupplyOrderRsp) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *CloseOrSupplyOrderRsp) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CloseOrSupplyOrderRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CloseOrSupplyOrderRsp) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CloseOrSupplyOrderRsp) GetTradeState() int32 {
	if x != nil {
		return x.TradeState
	}
	return 0
}

func (x *CloseOrSupplyOrderRsp) GetPayTime() string {
	if x != nil {
		return x.PayTime
	}
	return ""
}

func (x *CloseOrSupplyOrderRsp) GetOrderSuccessToken() string {
	if x != nil {
		return x.OrderSuccessToken
	}
	return ""
}

var File_trade_itg_proto protoreflect.FileDescriptor

const file_trade_itg_proto_rawDesc = "" +
	"\n" +
	"\x0ftrade_itg.proto\x12\ttrade_itg\"7\n" +
	"\x11C2cTransferPreReq\x12\"\n" +
	"\rbuyer_user_id\x18\x01 \x01(\tR\vbuyerUserId\"^\n" +
	"\x11C2cTransferPreRsp\x12\"\n" +
	"\rbuyer_user_id\x18\x01 \x01(\tR\vbuyerUserId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\"\x8d\x02\n" +
	"\x10C2cTransferDoReq\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\"\n" +
	"\rbuyer_user_id\x18\x02 \x01(\tR\vbuyerUserId\x12$\n" +
	"\x0eseller_user_id\x18\x03 \x01(\tR\fsellerUserId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x19\n" +
	"\bcur_type\x18\x05 \x01(\x05R\acurType\x12\x1f\n" +
	"\vverify_type\x18\x06 \x01(\x05R\n" +
	"verifyType\x12\x1a\n" +
	"\bpassword\x18\a \x01(\tR\bpassword\x12\x18\n" +
	"\aversion\x18\b \x01(\x05R\aversion\"\xa0\x01\n" +
	"\x10C2cTransferDoRsp\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\"\n" +
	"\rbuyer_user_id\x18\x02 \x01(\tR\vbuyerUserId\x12$\n" +
	"\x0eseller_user_id\x18\x03 \x01(\tR\fsellerUserId\x12\x1b\n" +
	"\tis_repeat\x18\x04 \x01(\x05R\bisRepeat\"'\n" +
	"\fBank2CPreReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"N\n" +
	"\fBank2CPreRsp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\"\xd3\x01\n" +
	"\vBank2CDoReq\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tbank_type\x18\x03 \x01(\x05R\bbankType\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x12\n" +
	"\x04desc\x18\x05 \x01(\tR\x04desc\x12\x1f\n" +
	"\vverify_type\x18\x06 \x01(\x05R\n" +
	"verifyType\x12\x1a\n" +
	"\bpassword\x18\a \x01(\tR\bpassword\"j\n" +
	"\vBank2CDoRsp\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tis_repeat\x18\x03 \x01(\x05R\bisRepeat\"'\n" +
	"\fC2BankPreReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"N\n" +
	"\fC2BankPreRsp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\"\xd3\x01\n" +
	"\vC2BankDoReq\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tbank_type\x18\x03 \x01(\x05R\bbankType\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x12\n" +
	"\x04desc\x18\x05 \x01(\tR\x04desc\x12\x1f\n" +
	"\vverify_type\x18\x06 \x01(\x05R\n" +
	"verifyType\x12\x1a\n" +
	"\bpassword\x18\a \x01(\tR\bpassword\"j\n" +
	"\vC2BankDoRsp\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tis_repeat\x18\x03 \x01(\x05R\bisRepeat\"E\n" +
	"\tPayPreReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\"K\n" +
	"\tPayPreRsp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\"\xe3\x01\n" +
	"\tBanPayReq\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12 \n" +
	"\fout_order_no\x18\x02 \x01(\tR\n" +
	"outOrderNo\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\tR\n" +
	"merchantId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x1f\n" +
	"\vverify_type\x18\x06 \x01(\x05R\n" +
	"verifyType\x12\x1a\n" +
	"\bpassword\x18\a \x01(\tR\bpassword\"\xf1\x01\n" +
	"\tBanPayRsp\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12 \n" +
	"\fout_order_no\x18\x02 \x01(\tR\n" +
	"outOrderNo\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1f\n" +
	"\vmerchant_id\x18\x04 \x01(\tR\n" +
	"merchantId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x19\n" +
	"\bpay_time\x18\x06 \x01(\tR\apayTime\x12.\n" +
	"\x13order_success_token\x18\a \x01(\tR\x11orderSuccessToken\"\xb2\x01\n" +
	"\x15CloseOrSupplyOrderReq\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12 \n" +
	"\fout_order_no\x18\x02 \x01(\tR\n" +
	"outOrderNo\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\tR\n" +
	"merchantId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\"\x85\x02\n" +
	"\x15CloseOrSupplyOrderRsp\x12\x1f\n" +
	"\vresult_code\x18\x01 \x01(\x05R\n" +
	"resultCode\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1f\n" +
	"\vmerchant_id\x18\x04 \x01(\tR\n" +
	"merchantId\x12\x1f\n" +
	"\vtrade_state\x18\x05 \x01(\x05R\n" +
	"tradeState\x12\x19\n" +
	"\bpay_time\x18\x06 \x01(\tR\apayTime\x12.\n" +
	"\x13order_success_token\x18\a \x01(\tR\x11orderSuccessToken2\xdf\x04\n" +
	"\bTradeItg\x12L\n" +
	"\x0eC2cTransferPre\x12\x1c.trade_itg.C2cTransferPreReq\x1a\x1c.trade_itg.C2cTransferPreRsp\x12I\n" +
	"\rC2cTransferDo\x12\x1b.trade_itg.C2cTransferDoReq\x1a\x1b.trade_itg.C2cTransferDoRsp\x12=\n" +
	"\tBank2CPre\x12\x17.trade_itg.Bank2CPreReq\x1a\x17.trade_itg.Bank2CPreRsp\x12:\n" +
	"\bBank2CDo\x12\x16.trade_itg.Bank2CDoReq\x1a\x16.trade_itg.Bank2CDoRsp\x12=\n" +
	"\tC2BankPre\x12\x17.trade_itg.C2BankPreReq\x1a\x17.trade_itg.C2BankPreRsp\x12:\n" +
	"\bC2BankDo\x12\x16.trade_itg.C2BankDoReq\x1a\x16.trade_itg.C2BankDoRsp\x124\n" +
	"\x06PayPre\x12\x14.trade_itg.PayPreReq\x1a\x14.trade_itg.PayPreRsp\x124\n" +
	"\x06BanPay\x12\x14.trade_itg.BanPayReq\x1a\x14.trade_itg.BanPayRsp\x12X\n" +
	"\x12CloseOrSupplyOrder\x12 .trade_itg.CloseOrSupplyOrderReq\x1a .trade_itg.CloseOrSupplyOrderRspB\x10Z\x0e./trade_itg_pbb\x06proto3"

var (
	file_trade_itg_proto_rawDescOnce sync.Once
	file_trade_itg_proto_rawDescData []byte
)

func file_trade_itg_proto_rawDescGZIP() []byte {
	file_trade_itg_proto_rawDescOnce.Do(func() {
		file_trade_itg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trade_itg_proto_rawDesc), len(file_trade_itg_proto_rawDesc)))
	})
	return file_trade_itg_proto_rawDescData
}

var file_trade_itg_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_trade_itg_proto_goTypes = []any{
	(*C2CTransferPreReq)(nil),     // 0: trade_itg.C2cTransferPreReq
	(*C2CTransferPreRsp)(nil),     // 1: trade_itg.C2cTransferPreRsp
	(*C2CTransferDoReq)(nil),      // 2: trade_itg.C2cTransferDoReq
	(*C2CTransferDoRsp)(nil),      // 3: trade_itg.C2cTransferDoRsp
	(*Bank2CPreReq)(nil),          // 4: trade_itg.Bank2CPreReq
	(*Bank2CPreRsp)(nil),          // 5: trade_itg.Bank2CPreRsp
	(*Bank2CDoReq)(nil),           // 6: trade_itg.Bank2CDoReq
	(*Bank2CDoRsp)(nil),           // 7: trade_itg.Bank2CDoRsp
	(*C2BankPreReq)(nil),          // 8: trade_itg.C2BankPreReq
	(*C2BankPreRsp)(nil),          // 9: trade_itg.C2BankPreRsp
	(*C2BankDoReq)(nil),           // 10: trade_itg.C2BankDoReq
	(*C2BankDoRsp)(nil),           // 11: trade_itg.C2BankDoRsp
	(*PayPreReq)(nil),             // 12: trade_itg.PayPreReq
	(*PayPreRsp)(nil),             // 13: trade_itg.PayPreRsp
	(*BanPayReq)(nil),             // 14: trade_itg.BanPayReq
	(*BanPayRsp)(nil),             // 15: trade_itg.BanPayRsp
	(*CloseOrSupplyOrderReq)(nil), // 16: trade_itg.CloseOrSupplyOrderReq
	(*CloseOrSupplyOrderRsp)(nil), // 17: trade_itg.CloseOrSupplyOrderRsp
}
var file_trade_itg_proto_depIdxs = []int32{
	0,  // 0: trade_itg.TradeItg.C2cTransferPre:input_type -> trade_itg.C2cTransferPreReq
	2,  // 1: trade_itg.TradeItg.C2cTransferDo:input_type -> trade_itg.C2cTransferDoReq
	4,  // 2: trade_itg.TradeItg.Bank2CPre:input_type -> trade_itg.Bank2CPreReq
	6,  // 3: trade_itg.TradeItg.Bank2CDo:input_type -> trade_itg.Bank2CDoReq
	8,  // 4: trade_itg.TradeItg.C2BankPre:input_type -> trade_itg.C2BankPreReq
	10, // 5: trade_itg.TradeItg.C2BankDo:input_type -> trade_itg.C2BankDoReq
	12, // 6: trade_itg.TradeItg.PayPre:input_type -> trade_itg.PayPreReq
	14, // 7: trade_itg.TradeItg.BanPay:input_type -> trade_itg.BanPayReq
	16, // 8: trade_itg.TradeItg.CloseOrSupplyOrder:input_type -> trade_itg.CloseOrSupplyOrderReq
	1,  // 9: trade_itg.TradeItg.C2cTransferPre:output_type -> trade_itg.C2cTransferPreRsp
	3,  // 10: trade_itg.TradeItg.C2cTransferDo:output_type -> trade_itg.C2cTransferDoRsp
	5,  // 11: trade_itg.TradeItg.Bank2CPre:output_type -> trade_itg.Bank2CPreRsp
	7,  // 12: trade_itg.TradeItg.Bank2CDo:output_type -> trade_itg.Bank2CDoRsp
	9,  // 13: trade_itg.TradeItg.C2BankPre:output_type -> trade_itg.C2BankPreRsp
	11, // 14: trade_itg.TradeItg.C2BankDo:output_type -> trade_itg.C2BankDoRsp
	13, // 15: trade_itg.TradeItg.PayPre:output_type -> trade_itg.PayPreRsp
	15, // 16: trade_itg.TradeItg.BanPay:output_type -> trade_itg.BanPayRsp
	17, // 17: trade_itg.TradeItg.CloseOrSupplyOrder:output_type -> trade_itg.CloseOrSupplyOrderRsp
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_trade_itg_proto_init() }
func file_trade_itg_proto_init() {
	if File_trade_itg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trade_itg_proto_rawDesc), len(file_trade_itg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trade_itg_proto_goTypes,
		DependencyIndexes: file_trade_itg_proto_depIdxs,
		MessageInfos:      file_trade_itg_proto_msgTypes,
	}.Build()
	File_trade_itg_proto = out.File
	file_trade_itg_proto_goTypes = nil
	file_trade_itg_proto_depIdxs = nil
}
