// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: trade_itg.proto

package trade_itg_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TradeItg_C2CTransferPre_FullMethodName = "/trade_itg.TradeItg/C2cTransferPre"
	TradeItg_C2CTransferDo_FullMethodName  = "/trade_itg.TradeItg/C2cTransferDo"
	TradeItg_Bank2CPre_FullMethodName      = "/trade_itg.TradeItg/Bank2CPre"
	TradeItg_Bank2CDo_FullMethodName       = "/trade_itg.TradeItg/Bank2CDo"
	TradeItg_C2BankPre_FullMethodName      = "/trade_itg.TradeItg/C2BankPre"
	TradeItg_C2BankDo_FullMethodName       = "/trade_itg.TradeItg/C2BankDo"
)

// TradeItgClient is the client API for TradeItg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradeItgClient interface {
	C2CTransferPre(ctx context.Context, in *C2CTransferPreReq, opts ...grpc.CallOption) (*C2CTransferPreRsp, error)
	C2CTransferDo(ctx context.Context, in *C2CTransferDoReq, opts ...grpc.CallOption) (*C2CTransferDoRsp, error)
	Bank2CPre(ctx context.Context, in *Bank2CPreReq, opts ...grpc.CallOption) (*Bank2CPreRsp, error)
	Bank2CDo(ctx context.Context, in *Bank2CDoReq, opts ...grpc.CallOption) (*Bank2CDoRsp, error)
	C2BankPre(ctx context.Context, in *C2BankPreReq, opts ...grpc.CallOption) (*C2BankPreRsp, error)
	C2BankDo(ctx context.Context, in *C2BankDoReq, opts ...grpc.CallOption) (*C2BankDoRsp, error)
}

type tradeItgClient struct {
	cc grpc.ClientConnInterface
}

func NewTradeItgClient(cc grpc.ClientConnInterface) TradeItgClient {
	return &tradeItgClient{cc}
}

func (c *tradeItgClient) C2CTransferPre(ctx context.Context, in *C2CTransferPreReq, opts ...grpc.CallOption) (*C2CTransferPreRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(C2CTransferPreRsp)
	err := c.cc.Invoke(ctx, TradeItg_C2CTransferPre_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeItgClient) C2CTransferDo(ctx context.Context, in *C2CTransferDoReq, opts ...grpc.CallOption) (*C2CTransferDoRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(C2CTransferDoRsp)
	err := c.cc.Invoke(ctx, TradeItg_C2CTransferDo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeItgClient) Bank2CPre(ctx context.Context, in *Bank2CPreReq, opts ...grpc.CallOption) (*Bank2CPreRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bank2CPreRsp)
	err := c.cc.Invoke(ctx, TradeItg_Bank2CPre_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeItgClient) Bank2CDo(ctx context.Context, in *Bank2CDoReq, opts ...grpc.CallOption) (*Bank2CDoRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bank2CDoRsp)
	err := c.cc.Invoke(ctx, TradeItg_Bank2CDo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeItgClient) C2BankPre(ctx context.Context, in *C2BankPreReq, opts ...grpc.CallOption) (*C2BankPreRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(C2BankPreRsp)
	err := c.cc.Invoke(ctx, TradeItg_C2BankPre_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeItgClient) C2BankDo(ctx context.Context, in *C2BankDoReq, opts ...grpc.CallOption) (*C2BankDoRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(C2BankDoRsp)
	err := c.cc.Invoke(ctx, TradeItg_C2BankDo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradeItgServer is the server API for TradeItg service.
// All implementations must embed UnimplementedTradeItgServer
// for forward compatibility.
type TradeItgServer interface {
	C2CTransferPre(context.Context, *C2CTransferPreReq) (*C2CTransferPreRsp, error)
	C2CTransferDo(context.Context, *C2CTransferDoReq) (*C2CTransferDoRsp, error)
	Bank2CPre(context.Context, *Bank2CPreReq) (*Bank2CPreRsp, error)
	Bank2CDo(context.Context, *Bank2CDoReq) (*Bank2CDoRsp, error)
	C2BankPre(context.Context, *C2BankPreReq) (*C2BankPreRsp, error)
	C2BankDo(context.Context, *C2BankDoReq) (*C2BankDoRsp, error)
	mustEmbedUnimplementedTradeItgServer()
}

// UnimplementedTradeItgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTradeItgServer struct{}

func (UnimplementedTradeItgServer) C2CTransferPre(context.Context, *C2CTransferPreReq) (*C2CTransferPreRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method C2CTransferPre not implemented")
}
func (UnimplementedTradeItgServer) C2CTransferDo(context.Context, *C2CTransferDoReq) (*C2CTransferDoRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method C2CTransferDo not implemented")
}
func (UnimplementedTradeItgServer) Bank2CPre(context.Context, *Bank2CPreReq) (*Bank2CPreRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method Bank2CPre not implemented")
}
func (UnimplementedTradeItgServer) Bank2CDo(context.Context, *Bank2CDoReq) (*Bank2CDoRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method Bank2CDo not implemented")
}
func (UnimplementedTradeItgServer) C2BankPre(context.Context, *C2BankPreReq) (*C2BankPreRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method C2BankPre not implemented")
}
func (UnimplementedTradeItgServer) C2BankDo(context.Context, *C2BankDoReq) (*C2BankDoRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method C2BankDo not implemented")
}
func (UnimplementedTradeItgServer) mustEmbedUnimplementedTradeItgServer() {}
func (UnimplementedTradeItgServer) testEmbeddedByValue()                  {}

// UnsafeTradeItgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradeItgServer will
// result in compilation errors.
type UnsafeTradeItgServer interface {
	mustEmbedUnimplementedTradeItgServer()
}

func RegisterTradeItgServer(s grpc.ServiceRegistrar, srv TradeItgServer) {
	// If the following call panics, it indicates UnimplementedTradeItgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TradeItg_ServiceDesc, srv)
}

func _TradeItg_C2CTransferPre_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(C2CTransferPreReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeItgServer).C2CTransferPre(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeItg_C2CTransferPre_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeItgServer).C2CTransferPre(ctx, req.(*C2CTransferPreReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeItg_C2CTransferDo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(C2CTransferDoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeItgServer).C2CTransferDo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeItg_C2CTransferDo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeItgServer).C2CTransferDo(ctx, req.(*C2CTransferDoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeItg_Bank2CPre_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Bank2CPreReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeItgServer).Bank2CPre(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeItg_Bank2CPre_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeItgServer).Bank2CPre(ctx, req.(*Bank2CPreReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeItg_Bank2CDo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Bank2CDoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeItgServer).Bank2CDo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeItg_Bank2CDo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeItgServer).Bank2CDo(ctx, req.(*Bank2CDoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeItg_C2BankPre_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(C2BankPreReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeItgServer).C2BankPre(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeItg_C2BankPre_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeItgServer).C2BankPre(ctx, req.(*C2BankPreReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeItg_C2BankDo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(C2BankDoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeItgServer).C2BankDo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeItg_C2BankDo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeItgServer).C2BankDo(ctx, req.(*C2BankDoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TradeItg_ServiceDesc is the grpc.ServiceDesc for TradeItg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradeItg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trade_itg.TradeItg",
	HandlerType: (*TradeItgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "C2cTransferPre",
			Handler:    _TradeItg_C2CTransferPre_Handler,
		},
		{
			MethodName: "C2cTransferDo",
			Handler:    _TradeItg_C2CTransferDo_Handler,
		},
		{
			MethodName: "Bank2CPre",
			Handler:    _TradeItg_Bank2CPre_Handler,
		},
		{
			MethodName: "Bank2CDo",
			Handler:    _TradeItg_Bank2CDo_Handler,
		},
		{
			MethodName: "C2BankPre",
			Handler:    _TradeItg_C2BankPre_Handler,
		},
		{
			MethodName: "C2BankDo",
			Handler:    _TradeItg_C2BankDo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trade_itg.proto",
}
