// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: trade_itg.proto

package trade_itg_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type C2CTransferPreReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuyerUserId   string                 `protobuf:"bytes,1,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2CTransferPreReq) Reset() {
	*x = C2CTransferPreReq{}
	mi := &file_trade_itg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2CTransferPreReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CTransferPreReq) ProtoMessage() {}

func (x *C2CTransferPreReq) ProtoReflect() protoreflect.Message {
	mi := &file_trade_itg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CTransferPreReq.ProtoReflect.Descriptor instead.
func (*C2CTransferPreReq) Descriptor() ([]byte, []int) {
	return file_trade_itg_proto_rawDescGZIP(), []int{0}
}

func (x *C2CTransferPreReq) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

type C2CTransferPreRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuyerUserId   string                 `protobuf:"bytes,1,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2CTransferPreRsp) Reset() {
	*x = C2CTransferPreRsp{}
	mi := &file_trade_itg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2CTransferPreRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CTransferPreRsp) ProtoMessage() {}

func (x *C2CTransferPreRsp) ProtoReflect() protoreflect.Message {
	mi := &file_trade_itg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CTransferPreRsp.ProtoReflect.Descriptor instead.
func (*C2CTransferPreRsp) Descriptor() ([]byte, []int) {
	return file_trade_itg_proto_rawDescGZIP(), []int{1}
}

func (x *C2CTransferPreRsp) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *C2CTransferPreRsp) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type C2CTransferDoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	BuyerUserId   string                 `protobuf:"bytes,2,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	SellerUserId  string                 `protobuf:"bytes,3,opt,name=seller_user_id,json=sellerUserId,proto3" json:"seller_user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	CurType       int32                  `protobuf:"varint,5,opt,name=cur_type,json=curType,proto3" json:"cur_type,omitempty"`
	VerifyType    int32                  `protobuf:"varint,6,opt,name=verify_type,json=verifyType,proto3" json:"verify_type,omitempty"`
	Password      string                 `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2CTransferDoReq) Reset() {
	*x = C2CTransferDoReq{}
	mi := &file_trade_itg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2CTransferDoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CTransferDoReq) ProtoMessage() {}

func (x *C2CTransferDoReq) ProtoReflect() protoreflect.Message {
	mi := &file_trade_itg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CTransferDoReq.ProtoReflect.Descriptor instead.
func (*C2CTransferDoReq) Descriptor() ([]byte, []int) {
	return file_trade_itg_proto_rawDescGZIP(), []int{2}
}

func (x *C2CTransferDoReq) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *C2CTransferDoReq) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *C2CTransferDoReq) GetSellerUserId() string {
	if x != nil {
		return x.SellerUserId
	}
	return ""
}

func (x *C2CTransferDoReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *C2CTransferDoReq) GetCurType() int32 {
	if x != nil {
		return x.CurType
	}
	return 0
}

func (x *C2CTransferDoReq) GetVerifyType() int32 {
	if x != nil {
		return x.VerifyType
	}
	return 0
}

func (x *C2CTransferDoReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type C2CTransferDoRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	BuyerUserId   string                 `protobuf:"bytes,2,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	SellerUserId  string                 `protobuf:"bytes,3,opt,name=seller_user_id,json=sellerUserId,proto3" json:"seller_user_id,omitempty"`
	IsRepeat      bool                   `protobuf:"varint,4,opt,name=is_repeat,json=isRepeat,proto3" json:"is_repeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2CTransferDoRsp) Reset() {
	*x = C2CTransferDoRsp{}
	mi := &file_trade_itg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2CTransferDoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CTransferDoRsp) ProtoMessage() {}

func (x *C2CTransferDoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_trade_itg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CTransferDoRsp.ProtoReflect.Descriptor instead.
func (*C2CTransferDoRsp) Descriptor() ([]byte, []int) {
	return file_trade_itg_proto_rawDescGZIP(), []int{3}
}

func (x *C2CTransferDoRsp) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *C2CTransferDoRsp) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *C2CTransferDoRsp) GetSellerUserId() string {
	if x != nil {
		return x.SellerUserId
	}
	return ""
}

func (x *C2CTransferDoRsp) GetIsRepeat() bool {
	if x != nil {
		return x.IsRepeat
	}
	return false
}

var File_trade_itg_proto protoreflect.FileDescriptor

const file_trade_itg_proto_rawDesc = "" +
	"\n" +
	"\x0ftrade_itg.proto\x12\ttrade_itg\"7\n" +
	"\x11C2cTransferPreReq\x12\"\n" +
	"\rbuyer_user_id\x18\x01 \x01(\tR\vbuyerUserId\"^\n" +
	"\x11C2cTransferPreRsp\x12\"\n" +
	"\rbuyer_user_id\x18\x01 \x01(\tR\vbuyerUserId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\"\xf3\x01\n" +
	"\x10C2cTransferDoReq\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\"\n" +
	"\rbuyer_user_id\x18\x02 \x01(\tR\vbuyerUserId\x12$\n" +
	"\x0eseller_user_id\x18\x03 \x01(\tR\fsellerUserId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x19\n" +
	"\bcur_type\x18\x05 \x01(\x05R\acurType\x12\x1f\n" +
	"\vverify_type\x18\x06 \x01(\x05R\n" +
	"verifyType\x12\x1a\n" +
	"\bpassword\x18\a \x01(\tR\bpassword\"\xa0\x01\n" +
	"\x10C2cTransferDoRsp\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\"\n" +
	"\rbuyer_user_id\x18\x02 \x01(\tR\vbuyerUserId\x12$\n" +
	"\x0eseller_user_id\x18\x03 \x01(\tR\fsellerUserId\x12\x1b\n" +
	"\tis_repeat\x18\x04 \x01(\bR\bisRepeat2\xa3\x01\n" +
	"\bTradeItg\x12L\n" +
	"\x0eC2cTransferPre\x12\x1c.trade_itg.C2cTransferPreReq\x1a\x1c.trade_itg.C2cTransferPreRsp\x12I\n" +
	"\rC2cTransferDo\x12\x1b.trade_itg.C2cTransferDoReq\x1a\x1b.trade_itg.C2cTransferDoRspB\x10Z\x0e./trade_itg_pbb\x06proto3"

var (
	file_trade_itg_proto_rawDescOnce sync.Once
	file_trade_itg_proto_rawDescData []byte
)

func file_trade_itg_proto_rawDescGZIP() []byte {
	file_trade_itg_proto_rawDescOnce.Do(func() {
		file_trade_itg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trade_itg_proto_rawDesc), len(file_trade_itg_proto_rawDesc)))
	})
	return file_trade_itg_proto_rawDescData
}

var file_trade_itg_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_trade_itg_proto_goTypes = []any{
	(*C2CTransferPreReq)(nil), // 0: trade_itg.C2cTransferPreReq
	(*C2CTransferPreRsp)(nil), // 1: trade_itg.C2cTransferPreRsp
	(*C2CTransferDoReq)(nil),  // 2: trade_itg.C2cTransferDoReq
	(*C2CTransferDoRsp)(nil),  // 3: trade_itg.C2cTransferDoRsp
}
var file_trade_itg_proto_depIdxs = []int32{
	0, // 0: trade_itg.TradeItg.C2cTransferPre:input_type -> trade_itg.C2cTransferPreReq
	2, // 1: trade_itg.TradeItg.C2cTransferDo:input_type -> trade_itg.C2cTransferDoReq
	1, // 2: trade_itg.TradeItg.C2cTransferPre:output_type -> trade_itg.C2cTransferPreRsp
	3, // 3: trade_itg.TradeItg.C2cTransferDo:output_type -> trade_itg.C2cTransferDoRsp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trade_itg_proto_init() }
func file_trade_itg_proto_init() {
	if File_trade_itg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trade_itg_proto_rawDesc), len(file_trade_itg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trade_itg_proto_goTypes,
		DependencyIndexes: file_trade_itg_proto_depIdxs,
		MessageInfos:      file_trade_itg_proto_msgTypes,
	}.Build()
	File_trade_itg_proto = out.File
	file_trade_itg_proto_goTypes = nil
	file_trade_itg_proto_depIdxs = nil
}
