// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: trade_itg.proto

package tradeitg

import (
	"context"

	"github.com/starslipay/trade_itg/trade_itg_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BanPayReq         = trade_itg_pb.BanPayReq
	BanPayRsp         = trade_itg_pb.BanPayRsp
	Bank2CDoReq       = trade_itg_pb.Bank2CDoReq
	Bank2CDoRsp       = trade_itg_pb.Bank2CDoRsp
	Bank2CPreReq      = trade_itg_pb.Bank2CPreReq
	Bank2CPreRsp      = trade_itg_pb.Bank2CPreRsp
	C2BankDoReq       = trade_itg_pb.C2BankDoReq
	C2BankDoRsp       = trade_itg_pb.C2BankDoRsp
	C2BankPreReq      = trade_itg_pb.C2BankPreReq
	C2BankPreRsp      = trade_itg_pb.C2BankPreRsp
	C2CTransferDoReq  = trade_itg_pb.C2CTransferDoReq
	C2CTransferDoRsp  = trade_itg_pb.C2CTransferDoRsp
	C2CTransferPreReq = trade_itg_pb.C2CTransferPreReq
	C2CTransferPreRsp = trade_itg_pb.C2CTransferPreRsp
	PayPreReq         = trade_itg_pb.PayPreReq
	PayPreRsp         = trade_itg_pb.PayPreRsp

	TradeItg interface {
		C2CTransferPre(ctx context.Context, in *C2CTransferPreReq, opts ...grpc.CallOption) (*C2CTransferPreRsp, error)
		C2CTransferDo(ctx context.Context, in *C2CTransferDoReq, opts ...grpc.CallOption) (*C2CTransferDoRsp, error)
		Bank2CPre(ctx context.Context, in *Bank2CPreReq, opts ...grpc.CallOption) (*Bank2CPreRsp, error)
		Bank2CDo(ctx context.Context, in *Bank2CDoReq, opts ...grpc.CallOption) (*Bank2CDoRsp, error)
		C2BankPre(ctx context.Context, in *C2BankPreReq, opts ...grpc.CallOption) (*C2BankPreRsp, error)
		C2BankDo(ctx context.Context, in *C2BankDoReq, opts ...grpc.CallOption) (*C2BankDoRsp, error)
		PayPre(ctx context.Context, in *PayPreReq, opts ...grpc.CallOption) (*PayPreRsp, error)
		BanPay(ctx context.Context, in *BanPayReq, opts ...grpc.CallOption) (*BanPayRsp, error)
	}

	defaultTradeItg struct {
		cli zrpc.Client
	}
)

func NewTradeItg(cli zrpc.Client) TradeItg {
	return &defaultTradeItg{
		cli: cli,
	}
}

func (m *defaultTradeItg) C2CTransferPre(ctx context.Context, in *C2CTransferPreReq, opts ...grpc.CallOption) (*C2CTransferPreRsp, error) {
	client := trade_itg_pb.NewTradeItgClient(m.cli.Conn())
	return client.C2CTransferPre(ctx, in, opts...)
}

func (m *defaultTradeItg) C2CTransferDo(ctx context.Context, in *C2CTransferDoReq, opts ...grpc.CallOption) (*C2CTransferDoRsp, error) {
	client := trade_itg_pb.NewTradeItgClient(m.cli.Conn())
	return client.C2CTransferDo(ctx, in, opts...)
}

func (m *defaultTradeItg) Bank2CPre(ctx context.Context, in *Bank2CPreReq, opts ...grpc.CallOption) (*Bank2CPreRsp, error) {
	client := trade_itg_pb.NewTradeItgClient(m.cli.Conn())
	return client.Bank2CPre(ctx, in, opts...)
}

func (m *defaultTradeItg) Bank2CDo(ctx context.Context, in *Bank2CDoReq, opts ...grpc.CallOption) (*Bank2CDoRsp, error) {
	client := trade_itg_pb.NewTradeItgClient(m.cli.Conn())
	return client.Bank2CDo(ctx, in, opts...)
}

func (m *defaultTradeItg) C2BankPre(ctx context.Context, in *C2BankPreReq, opts ...grpc.CallOption) (*C2BankPreRsp, error) {
	client := trade_itg_pb.NewTradeItgClient(m.cli.Conn())
	return client.C2BankPre(ctx, in, opts...)
}

func (m *defaultTradeItg) C2BankDo(ctx context.Context, in *C2BankDoReq, opts ...grpc.CallOption) (*C2BankDoRsp, error) {
	client := trade_itg_pb.NewTradeItgClient(m.cli.Conn())
	return client.C2BankDo(ctx, in, opts...)
}

func (m *defaultTradeItg) PayPre(ctx context.Context, in *PayPreReq, opts ...grpc.CallOption) (*PayPreRsp, error) {
	client := trade_itg_pb.NewTradeItgClient(m.cli.Conn())
	return client.PayPre(ctx, in, opts...)
}

func (m *defaultTradeItg) BanPay(ctx context.Context, in *BanPayReq, opts ...grpc.CallOption) (*BanPayRsp, error) {
	client := trade_itg_pb.NewTradeItgClient(m.cli.Conn())
	return client.BanPay(ctx, in, opts...)
}
