// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: trade_itg.proto

package tradeitg

import (
	"context"

	"github.com/starslipay/trade_itg/trade_itg_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	C2CTransferDoReq  = trade_itg_pb.C2CTransferDoReq
	C2CTransferDoRsp  = trade_itg_pb.C2CTransferDoRsp
	C2CTransferPreReq = trade_itg_pb.C2CTransferPreReq
	C2CTransferPreRsp = trade_itg_pb.C2CTransferPreRsp

	TradeItg interface {
		C2CTransferPre(ctx context.Context, in *C2CTransferPreReq, opts ...grpc.CallOption) (*C2CTransferPreRsp, error)
		C2CTransferDo(ctx context.Context, in *C2CTransferDoReq, opts ...grpc.CallOption) (*C2CTransferDoRsp, error)
	}

	defaultTradeItg struct {
		cli zrpc.Client
	}
)

func NewTradeItg(cli zrpc.Client) TradeItg {
	return &defaultTradeItg{
		cli: cli,
	}
}

func (m *defaultTradeItg) C2CTransferPre(ctx context.Context, in *C2CTransferPreReq, opts ...grpc.CallOption) (*C2CTransferPreRsp, error) {
	client := trade_itg_pb.NewTradeItgClient(m.cli.Conn())
	return client.C2CTransferPre(ctx, in, opts...)
}

func (m *defaultTradeItg) C2CTransferDo(ctx context.Context, in *C2CTransferDoReq, opts ...grpc.CallOption) (*C2CTransferDoRsp, error) {
	client := trade_itg_pb.NewTradeItgClient(m.cli.Conn())
	return client.C2CTransferDo(ctx, in, opts...)
}
